### ISSUE TITLE
Add Error handling or check filepath before proceed readfile.

### ISSUE THREAD

**Issue by fadingNA** [aldrin312/AutoCommentingTool#3]
https://github.com/aldrin312/AutoCommentingTool/blob/0a92be444b052f54d79ada889570c9e01a54b887/index.js#L34

Better approach to have file path validation first before proceed read file other can crash the application. 

Also good idea if we have error handling here.

**Comment by aldrin312** [comment]
Thank you, I didn't think about to check if the files are valid or not.
Possibly I also need to check if they are the right file formats, like make sure files ends in .cpp, .js, .ts etc...

**Comment by fadingNA** [comment]
Yes I agreed, because we need to make sure we can handle docx, pdf, those unstrcutred format..

**Comment by aldrin312** [comment]
For now added the error handing for invalid files (exist or not).
