### ISSUE TITLE
Using async for writeFile 

### ISSUE THREAD

**Issue by fadingNA** [aldrin312/AutoCommentingTool#4]
https://github.com/aldrin312/AutoCommentingTool/blob/0a92be444b052f54d79ada889570c9e01a54b887/index.js#L47

using asynchonous to dealing with file even read or load, better because you can use async with error handling, easier for debug and not crash the application

**Comment by aldrin312** [comment]
Fixed!
asynced the writeIntoFile function.

**Comment by fadingNA** [comment]
@aldrin312  You may wan to 

```javascript

try{
  // processing file 
  
  return . 
}catch(err)
 console.error(`Error from write file ${err} ...`
 return .. 

```

you might wrap it with try catch block better for debug
